# Generated by Django 5.2.7 on 2025-11-07 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_customer_service_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rating.customer'),
            preserve_default=False,
        ),
    ]
