# Generated by Django 5.2.7 on 2025-11-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_alter_service_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='udr',
            name='usage_class',
            field=models.CharField(default='default_usage_class', max_length=50),
            preserve_default=False,
        ),
    ]
