# Generated by Django 5.2.7 on 2025-11-09 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_udr_usage_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='udr',
            name='raw',
            field=models.JSONField(default={'source': 'migration'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='udr',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
