# Generated by Django 5.2.7 on 2025-11-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_udr_raw_udr_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='udr',
            name='rated_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
