# Generated by Django 5.2.7 on 2025-11-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_udr_rated_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
