# Generated by Django 5.2.7 on 2025-11-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0010_promotion_remove_service_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
