# Generated by Django 5.2.7 on 2025-11-11 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0012_service_active_from_service_active_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='udr',
            name='billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='udr',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='udr',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udrs', to='rating.service'),
        ),
    ]
