# Generated by Django 5.2.7 on 2025-11-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0013_udr_billed_udr_currency_alter_udr_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_before_tax', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rating.customer')),
            ],
        ),
    ]
